version: "3.8"
services:
#======================================================  DATABASE CONTAINER =============================================
  db:
    image: ghcr.io/baharehtorki/groupmysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    expose:
      - '3306'
#======================================================  CUSTOMER CONTAINER =============================================
  customer-service:
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    image: ghcr.io/baharehtorki/customer:latest
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  wait-for-db:
      image: atkrad/wait4x
      depends_on:
        - db
      command: tcp db:3306 -t 30s -i 250ms
#======================================================  ORDER CONTAINERS =============================================
  order-service:
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    image: ghcr.io/idacjohansson/order:latest
    volumes:
      - ./app:/app

#======================================================  ITEM CONTAINER =============================================
  item-service:
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    image: ghcr.io/baharehtorki/item:latest
    volumes:
      - ./app:/app
