version: "3"
services:
#======================================================  DATABASE CONTAINER =============================================
  db:
    image: ghcr.io/baharehtorki/groupmysql:latest
    restart: always
    ports:
      - "3307:3306"
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

#======================================================  CUSTOMER CONTAINER =============================================
  customer-service:
    depends_on:
      - db
    image: ghcr.io/baharehtorki/customer:latest
    ports:
      - "8081:8080"
    volumes:
      - ./app:/app
#======================================================  ORDER CONTAINERS =============================================
#  item-service:
#    depends_on:
#      - customer_db
#    image: ghcr.io/baharehtorki/customer:latest
#    ports:
#      - "8081:8080"
#    volumes:
#      - ./app:/app

#======================================================  ITEM CONTAINERS =============================================
# Names our volume
volumes:
  my-db:
