version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '33088:3306'
    volumes:
      - db:/var/lib/mysql
      - ./init/script.sql:/docker-entrypoint-initdb.d/script.sql
volumes:
  db:
    driver: local